### PR TITLE
fix: Claymate bar on top of side menu

### PR DESCRIPTION
**Pull request by raphaelbs**
Fixes https://github.com/dai-shi/excalidraw-claymate/pull/8#issuecomment-799787047 by:
1. cropping the preview on the left to prevent hiding the side menu;
2. moving the buttons to the right;

### CODE REVIEW

**Comment by dai-shi** [comment]
Good idea. It think it's good.

Should we deal with this?

https://user-images.githubusercontent.com/490574/111246476-ab52d880-8649-11eb-9d5c-fbb072819988.mov

**Comment by dai-shi** [comment]
Also noticed another bug, which must have existed before recent changes.
The circle is in the video is different between snapshots and canvas.

**Comment by raphaelbs** [comment]
@dai-shi can you describe how to reproduce the circle bug?

**Comment by dai-shi** [comment]
Hmm, can't repro now. I'll file an issue when I found it.

Merging this.

**Pull request merged**
