### PR TITLE
HTML slide navigation buttons and current slide indicator

### PR DESCRIPTION
**Pull request by grant-davidson**
q2G09pYmDL

### CODE REVIEW

**Comment by dai-shi** [comment]
Yay, this looks nice! People would know how to use it. I would like to have a way to hide the navigation too for presentation mode.

**Comment by grant-davidson** [comment]
> Yay, this looks nice! People would know how to use it. I would like to have a way to hide the navigation too for presentation mode.

Yes, I think that would be useful.  I'll have a look

**Comment by grant-davidson** [comment]
yOhj7WYQ7T

**Comment by dai-shi** [comment]
Looks good! nice work.

**Review by dai-shi — APPROVED** [review]
Looks great.
As we add more features in html, we might want something more organized. Will see in the future.

**Pull request merged**
