### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by dai-shi**
(...all of them, except for `react-scripts`.)

### CODE REVIEW

**Review by grant-davidson — COMMENTED** [review]
Good to get the dev dependencies sorted!

**Review by grant-davidson — APPROVED** [review]

**Comment by dai-shi** [comment]
@grant-davidson (I should have noted here too.)
This breaks the saving to localStorage feature. Do you know how to fix?

**Comment by grant-davidson** [comment]
> @grant-davidson (I should have noted here too.)
> This breaks the saving to localStorage feature. Do you know how to fix?

I'll see if I can resolve this tonight

**Comment by dai-shi** [comment]
Thaaaanks!

**Pull request merged**
