### PR TITLE
feat: recording video in exported html

### PR DESCRIPTION
**Pull request by dai-shi**
If you export to html and then open the html file in Chrome, you can record video of your slides (with or without animations).

## Steps without audio

1. Click record button
2. Select Chrome Tab in screen sharing
3. Deny microphone access
4. (after finished) Stop screen sharing

## Steps with audio

1. Click record button
2. Select Chrome Tab in screen sharing
3. Allow microphone access
4. (after finished) Stop screen sharing
5. Click the record button again to save file

---

https://user-images.githubusercontent.com/490574/130374726-46553208-3834-46a1-969c-07e53d0ec228.mov

### CODE REVIEW

**Review by grant-davidson — APPROVED** [review]
Very nice!

**Comment by grant-davidson** [comment]
Are you planning to add the usage instructions to the readme?

**Comment by dai-shi** [comment]
good point. do you have an idea to improve the description in README?

**Comment by grant-davidson** [comment]
At some stage we should probably add some documentation that is accessible from the app itself (similar to or replacing the excalidraw help) but I think the pull request link is ok for now.

**Review by grant-davidson — APPROVED** [review]

**Comment by dai-shi** [comment]
Thanks!

**Pull request merged**
