### PR TITLE
feat: export to html

### PR DESCRIPTION
**Pull request by dai-shi**
and you can move scenes with right and left arrow keys.

### CODE REVIEW

**Comment by grant-davidson** [comment]
Nice feature!

**Review by grant-davidson — APPROVED** [review]
That works well! 
Good to get rid of the deprecated file save package as well

**Review by grant-davidson — DISMISSED** [review]
Another useful improvement!

**Comment by dai-shi** [comment]
Yay!


https://user-images.githubusercontent.com/490574/116799217-4d634d00-ab32-11eb-90c1-8be369dfeee8.mov

**Pull request merged**
