### PR TITLE
feat: update excalidraw package and others

### PR DESCRIPTION
**Pull request by dai-shi**
related: https://github.com/dai-shi/excalidraw-animate/pull/28

### CODE REVIEW

**Review by grant-davidson — APPROVED** [review]
Looks like exportToCanvas changing to async caused a cascade of changes!

**Review by grant-davidson — COMMENTED** [review]
Even if I delete all scenes from the app and then clear all site data, every time I refresh the page I get a new scene added

**Comment by grant-davidson** [comment]
The "new scene on every refresh" problem happens on the deploy for this branch as well

**Comment by grant-davidson** [comment]
The problem stems from the useEffect in useScenes which seems to be asynchronously triggering itself

**Comment by grant-davidson** [comment]
I'm working on a fix for this

**Review by dai-shi — COMMENTED** [review]
Cool. Thanks for the fix!
Is this ready for merge?

**Review by grant-davidson — APPROVED** [review]
Good to go

**Comment by dai-shi** [comment]
Great! Merging.

**Pull request merged**
