### PR TITLE
feat: animateDuration config

### PR DESCRIPTION
**Pull request by dai-shi**
code is slightly duplicated. there might be room for refactoring.
it would be nice to somehow tell `animateDuration` is in milliseconds.

### CODE REVIEW

**Review by grant-davidson — COMMENTED** [review]
Is this the total duration of the animation for the element?  If so, presumably the default isn't 0 milliseconds.

**Comment by dai-shi** [comment]
In `excalidraw-animate`, if it's `animateDuration` is falsy including `0`, it will use the default value. I know it's confusing. Any suggestion, UI-wise?

**Comment by grant-davidson** [comment]
Input placeholder of "Default" and label of "Animate duration (ms)" ?

**Comment by dai-shi** [comment]
> "Animate duration (ms)"

Looks good!

> Input placeholder of "Default"

Yeah, then we need to give up `type="number"`, right?
I think it's fine. I'll do this.

**Review by grant-davidson — APPROVED** [review]
That works well

**Pull request merged**
